export const categories = [
  { id: 'all', label: 'All Tools', icon: 'grid' },
  { id: 'compress-resize', label: 'Compress & Resize', icon: 'compress' },
  { id: 'convert', label: 'Format Converters', icon: 'refresh-cw' },
  { id: 'creative', label: 'Creative', icon: 'sparkles' },
  { id: 'utilities', label: 'Utilities', icon: 'tools' },
  { id: 'pdf', label: 'PDF Tools', icon: 'pdf' },
];

export const toolsData = [
  // ── Compress & Resize ──
  {
    id: 'image-studio',
    name: 'Image Studio',
    href: '/image-studio',
    category: 'compress-resize',
    badge: 'ALL-IN-ONE',
    trending: true,
    featured: true,
    description: 'All-in-one browser editor with instant compression, resizing, rotation, flipping, and live compare slider.',
    keywords: ['studio', 'all-in-one', 'editor', 'compress', 'resize', 'rotate', 'flip', 'canvas'],
    icon: 'image',
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    href: '/compress',
    category: 'compress-resize',
    badge: 'POPULAR',
    trending: true,
    featured: true,
    description: 'Compress JPG, PNG, and WebP images by up to 80% with adjustable quality and batch ZIP download.',
    keywords: ['compress', 'shrink', 'reduce size', 'tinypng', 'kb', 'mb', 'optimization'],
    icon: 'compress',
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    href: '/resize',
    category: 'compress-resize',
    badge: 'ESSENTIAL',
    trending: true,
    description: 'Resize images by pixels or percentage while maintaining exact aspect ratio.',
    keywords: ['resize', 'scale', 'dimensions', 'width', 'height', 'resolution'],
    icon: 'resize',
  },
  {
    id: 'bulk-resize',
    name: 'Bulk Image Resizer',
    href: '/bulk-resize',
    category: 'compress-resize',
    badge: 'BATCH',
    trending: false,
    description: 'Batch resize multiple images at once with custom widths, heights, and aspect ratio locking.',
    keywords: ['bulk', 'batch', 'mass', 'multiple', 'resize', 'scale'],
    icon: 'layers',
  },
  {
    id: 'crop-image',
    name: 'Crop Image',
    href: '/crop',
    category: 'compress-resize',
    badge: 'FAST',
    trending: false,
    description: 'Crop images with preset social media aspect ratios (1:1, 16:9, 4:3, 9:16) or custom freeform crops.',
    keywords: ['crop', 'cut', 'trim', 'aspect ratio', 'square', 'story'],
    icon: 'crop',
  },
  {
    id: 'compress-jpg',
    name: 'Compress JPG',
    href: '/compress-jpg',
    category: 'compress-resize',
    badge: 'JPEG',
    trending: false,
    description: 'Reduce JPEG image size while keeping crisp visual quality and stripping bloat.',
    keywords: ['compress jpg', 'compress jpeg', 'shrink jpg', 'reduce jpg size'],
    icon: 'file-text',
  },
  {
    id: 'compress-png',
    name: 'Compress PNG',
    href: '/compress-png',
    category: 'compress-resize',
    badge: 'LOSSLESS',
    trending: false,
    description: 'Optimize PNG images with transparent backgrounds to the smallest possible file size.',
    keywords: ['compress png', 'shrink png', 'transparent', 'png optimization'],
    icon: 'image',
  },
  {
    id: 'compress-gif',
    name: 'Compress GIF',
    href: '/compress-gif',
    category: 'compress-resize',
    badge: 'ANIMATED',
    trending: false,
    description: 'Shrink animated GIF file sizes for faster loading on Discord, Slack, and websites.',
    keywords: ['compress gif', 'reduce gif size', 'smaller gif', 'discord gif'],
    icon: 'film',
  },
  {
    id: 'rotate-image',
    name: 'Rotate Image',
    href: '/rotate',
    category: 'compress-resize',
    badge: 'UTILITY',
    trending: false,
    description: 'Rotate images by 90°, 180°, or any custom angle clockwise and counter-clockwise.',
    keywords: ['rotate', 'turn', 'angle', 'orientation', 'tilt'],
    icon: 'rotate-cw',
  },
  {
    id: 'flip-image',
    name: 'Flip Image',
    href: '/flip',
    category: 'compress-resize',
    badge: 'UTILITY',
    trending: false,
    description: 'Mirror images horizontally or vertically in a single click with instant live preview.',
    keywords: ['flip', 'mirror', 'invert', 'reverse', 'horizontal', 'vertical'],
    icon: 'flip',
  },

  // ── Format Converters ──
  {
    id: 'image-converter',
    name: 'Universal Image Converter',
    href: '/image-converter',
    category: 'convert',
    badge: 'POPULAR',
    trending: true,
    description: 'Convert between JPEG, PNG, WebP, GIF, SVG, BMP, and ICO formats with batch ZIP export.',
    keywords: ['convert', 'format', 'jpeg to png', 'png to webp', 'ico', 'svg'],
    icon: 'refresh-cw',
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    href: '/png-to-jpg',
    category: 'convert',
    badge: 'FAST',
    trending: true,
    description: 'Convert transparent or solid PNG graphics into lightweight JPEG images instantly.',
    keywords: ['png to jpg', 'png to jpeg', 'convert png', 'jpg converter'],
    icon: 'arrow-right',
  },
  {
    id: 'webp-to-jpg',
    name: 'WebP to JPG',
    href: '/webp-to-jpg',
    category: 'convert',
    badge: 'CONVERT',
    trending: false,
    description: 'Turn Google WebP images from web downloads into universally compatible JPG files.',
    keywords: ['webp to jpg', 'webp to jpeg', 'convert webp', 'download webp as jpg'],
    icon: 'arrow-right',
  },
  {
    id: 'webp-to-png',
    name: 'WebP to PNG',
    href: '/webp-to-png',
    category: 'convert',
    badge: 'TRANSPARENT',
    trending: false,
    description: 'Convert WebP to PNG with transparent alpha channel intact and zero compression artifacts.',
    keywords: ['webp to png', 'transparent webp', 'save webp as png'],
    icon: 'arrow-right',
  },
  {
    id: 'heic-to-jpg',
    name: 'HEIC to JPG',
    href: '/heic-to-jpg',
    category: 'convert',
    badge: 'IPHONE',
    trending: false,
    description: 'Convert Apple iPhone HEIC/HEIF photos into standard JPG files directly in your browser.',
    keywords: ['heic', 'heif', 'iphone photo', 'apple photo', 'heic to jpg'],
    icon: 'smartphone',
  },
  {
    id: 'png-to-svg',
    name: 'PNG to SVG Vector',
    href: '/png-to-svg',
    category: 'convert',
    badge: 'VECTOR',
    trending: false,
    description: 'Trace and convert raster PNG images and logos into infinitely scalable SVG vectors.',
    keywords: ['png to svg', 'vectorize', 'trace', 'raster to vector', 'scalable'],
    icon: 'pen-tool',
  },
  {
    id: 'svg-rasterizer',
    name: 'SVG Rasterizer',
    href: '/svg-rasterizer',
    category: 'convert',
    badge: 'RASTER',
    trending: false,
    description: 'Render SVG vector graphics into high-resolution PNG or JPG images at any custom dimension.',
    keywords: ['svg to png', 'svg to jpg', 'rasterize', 'export svg'],
    icon: 'maximize',
  },
  {
    id: 'avif-to-jpg',
    name: 'AVIF to JPG',
    href: '/avif-to-jpg',
    category: 'convert',
    badge: 'NEW',
    trending: false,
    description: 'Convert modern next-gen AVIF images into standard JPG formats effortlessly.',
    keywords: ['avif to jpg', 'avif converter', 'next-gen image'],
    icon: 'arrow-right',
  },
  {
    id: 'tiff-to-jpg',
    name: 'TIFF to JPG',
    href: '/tiff-to-jpg',
    category: 'convert',
    badge: 'PRINT',
    trending: false,
    description: 'Convert large uncompressed TIFF/TIF scans and photography files into web-friendly JPGs.',
    keywords: ['tiff to jpg', 'tif', 'scanner file', 'print photography'],
    icon: 'file',
  },
  {
    id: 'bmp-to-jpg',
    name: 'BMP to JPG',
    href: '/bmp-to-jpg',
    category: 'convert',
    badge: 'LEGACY',
    trending: false,
    description: 'Convert heavy Windows Bitmap (.bmp) files into optimized lightweight JPG images.',
    keywords: ['bmp to jpg', 'bitmap to jpg', 'windows bitmap'],
    icon: 'file',
  },
  {
    id: 'gif-converter',
    name: 'GIF Converter',
    href: '/gif-converter',
    category: 'convert',
    badge: 'ANIMATION',
    trending: false,
    description: 'Convert GIF frames and animations into static images or other media formats.',
    keywords: ['gif converter', 'gif to jpg', 'gif to png'],
    icon: 'film',
  },
  {
    id: 'gif-maker',
    name: 'GIF Maker',
    href: '/gif-maker',
    category: 'convert',
    badge: 'CREATE',
    trending: false,
    description: 'Combine multiple photos into an animated GIF with custom frame delay and looping controls.',
    keywords: ['gif maker', 'create gif', 'animate photos', 'slideshow gif'],
    icon: 'video',
  },

  // ── Creative & Social ──
  {
    id: 'whiteboard',
    name: 'Whiteboard & Diagrams',
    href: '/whiteboard',
    category: 'creative',
    badge: 'NEW',
    trending: true,
    featured: true,
    description: 'Freehand whiteboard and diagram studio. Create flowcharts, wireframes, sketch notes, and annotate images privately.',
    keywords: ['whiteboard', 'excalidraw', 'diagram', 'sketch', 'draw', 'flowchart', 'wireframe', 'mindmap', 'annotate'],
    icon: 'pen-tool',
  },
  {
    id: 'meme-generator',
    name: 'Meme Generator',
    href: '/meme-generator',
    category: 'creative',
    badge: 'CREATIVE',
    trending: true,
    description: 'Create viral memes with custom top & bottom text, Impact font, text outline, and custom stickers.',
    keywords: ['meme', 'meme generator', 'impact font', 'funny', 'social media meme'],
    icon: 'smile',
  },
  {
    id: 'palette-extractor',
    name: 'Color Palette Extractor',
    href: '/palette-extractor',
    category: 'creative',
    badge: 'DESIGNER',
    trending: true,
    description: 'Extract dominant color palettes and HEX/RGB codes from any photo with single-click copying.',
    keywords: ['palette', 'color extractor', 'hex codes', 'rgb', 'dominant colors', 'color picker'],
    icon: 'droplet',
  },
  {
    id: 'photo-filters',
    name: 'Photo Filters & Effects',
    href: '/filters',
    category: 'creative',
    badge: 'EFFECTS',
    trending: false,
    description: 'Apply vintage, black & white, sepia, contrast, brightness, blur, and color grading filters.',
    keywords: ['filters', 'effects', 'vintage', 'sepia', 'grayscale', 'saturation'],
    icon: 'sliders',
  },
  {
    id: 'image-watermarker',
    name: 'Image Watermarker',
    href: '/watermark',
    category: 'creative',
    badge: 'PROTECT',
    trending: false,
    description: 'Protect your visual work by stamping customizable text or logo watermarks across your photos.',
    keywords: ['watermark', 'copyright', 'protect photo', 'branding', 'stamp logo'],
    icon: 'shield',
  },
  {
    id: 'collage-maker',
    name: 'Photo Collage Maker',
    href: '/collage',
    category: 'creative',
    badge: 'LAYOUTS',
    trending: false,
    description: 'Assemble multiple pictures into creative split-grid collages with customizable borders and spacing.',
    keywords: ['collage', 'photo grid', 'combine images', 'side by side', 'montage'],
    icon: 'grid',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art Generator',
    href: '/pixelator',
    category: 'creative',
    badge: 'RETRO',
    trending: false,
    description: 'Transform normal photographs into retro 8-bit, 16-bit, and mosaic pixel art graphics.',
    keywords: ['pixel art', 'pixelate', '8bit', '16bit', 'retro gaming', 'mosaic'],
    icon: 'box',
  },

  // ── Utilities ──
  {
    id: 'ocr-extractor',
    name: 'Image OCR Text Extractor',
    href: '/ocr',
    category: 'utilities',
    badge: 'AI / OCR',
    trending: true,
    description: 'Extract editable text from scanned documents, screenshots, receipts, and book pages accurately.',
    keywords: ['ocr', 'text extractor', 'image to text', 'scan to text', 'tesseract', 'read image'],
    icon: 'file-text',
  },
  {
    id: 'qr-generator',
    name: 'QR Code & Barcode Generator',
    href: '/qr-generator',
    category: 'utilities',
    badge: 'UTILITY',
    trending: true,
    description: 'Generate high-resolution QR codes for websites, WiFi, vCards, text, and ISBN barcodes.',
    keywords: ['qr code', 'barcode', 'qr generator', 'wifi qr', 'vcard', 'scan code'],
    icon: 'qr-code',
  },
  {
    id: 'bulk-rename',
    name: 'Bulk File Renamer',
    href: '/bulk-rename',
    category: 'utilities',
    badge: 'PRODUCTIVITY',
    trending: false,
    description: 'Rename batches of image files using custom prefixes, dates, numbering sequences, and find/replace.',
    keywords: ['bulk rename', 'batch rename', 'file organizer', 'number files'],
    icon: 'edit-3',
  },
  {
    id: 'exif-metadata',
    name: 'EXIF Metadata Stripper',
    href: '/metadata',
    category: 'utilities',
    badge: 'PRIVACY',
    trending: false,
    description: 'Inspect and wipe GPS location coordinates, camera models, and private EXIF data from photos.',
    keywords: ['exif', 'metadata', 'strip exif', 'remove gps', 'privacy', 'camera info'],
    icon: 'eye-off',
  },
  {
    id: 'generate-metadata',
    name: 'Generate Image Metadata',
    href: '/generate-metadata',
    category: 'utilities',
    badge: 'SEO',
    trending: false,
    description: 'Generate SEO-friendly alt text, titles, descriptions, and metadata tags for your image assets.',
    keywords: ['image metadata', 'alt text', 'seo image', 'image tags'],
    icon: 'tag',
  },
  // ── PDF Tools ──
  {
    id: 'image-to-pdf',
    name: 'Image to PDF Converter',
    href: '/image-to-pdf',
    category: 'pdf',
    badge: 'DOCUMENT',
    trending: false,
    description: 'Convert JPG, PNG, and WebP images into a single clean, shareable PDF document.',
    keywords: ['image to pdf', 'jpg to pdf', 'photo to pdf', 'convert to pdf'],
    icon: 'file-plus',
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images Extractor',
    href: '/pdf-to-images',
    category: 'pdf',
    badge: 'DOCUMENT',
    trending: false,
    description: 'Extract every page of a PDF file into high-resolution JPG or PNG image files.',
    keywords: ['pdf to images', 'pdf to jpg', 'pdf to png', 'extract pages'],
    icon: 'download',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    href: '/compress-pdf',
    category: 'pdf',
    badge: 'DOCUMENT',
    trending: false,
    description: 'Reduce PDF file sizes dramatically for email attachments while keeping text crisp.',
    keywords: ['compress pdf', 'reduce pdf size', 'smaller pdf'],
    icon: 'minimize-2',
  },
  {
    id: 'add-remove-pdf-pages',
    name: 'Add or Remove PDF Pages',
    href: '/add-remove-pdf-pages',
    category: 'pdf',
    badge: 'DOCUMENT',
    trending: false,
    description: 'Reorder, delete unwanted pages, or insert new pages into any existing PDF document.',
    keywords: ['edit pdf', 'delete pdf pages', 'reorder pdf', 'pdf editor'],
    icon: 'copy',
  },
  {
    id: 'pdf-converter',
    name: 'PDF Converter',
    href: '/pdf-converter',
    category: 'pdf',
    badge: 'CONVERT',
    trending: false,
    description: 'Two-way PDF conversion: export PDF pages as JPG/PNG or turn photo collections into PDFs.',
    keywords: ['pdf converter', 'pdf to image', 'image to pdf', 'convert pdf'],
    icon: 'file-text',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    href: '/jpg-to-pdf',
    category: 'pdf',
    badge: 'FAST',
    trending: false,
    description: 'Convert single or multiple JPG images into a clean, shareable PDF document.',
    keywords: ['jpg to pdf', 'jpeg to pdf', 'convert jpg to pdf'],
    icon: 'file-plus',
  },
  {
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    href: '/png-to-pdf',
    category: 'pdf',
    badge: 'DOCUMENT',
    trending: false,
    description: 'Convert PNG graphics and illustrations into PDF format with original quality preserved.',
    keywords: ['png to pdf', 'convert png to pdf', 'transparent png to pdf'],
    icon: 'file-plus',
  },
];
